Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/*
    - test/dummy/bin/*

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - test/dummy/config/application.rb
    - lib/activity_calendar/railtie.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
  Max: 30

Metrics/AbcSize:
  Exclude:
    - db/migrate/*
  Max: 30

Metrics/BlockLength:
  Exclude:
    - config/environments/*

Lint/SendWithMixinArgument:
  Enabled: false

# New cops (0.81)

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
